" Be iMproved
if &compatible
  set nocompatible
endif

" --- jetpack

set rtp+=~/.vim/pack/ext/start/vim-jetpack

call jetpack#begin()

call jetpack#add('airblade/vim-gitgutter')
call jetpack#add('ryanoasis/vim-devicons')
call jetpack#add('bling/vim-airline')
call jetpack#add('tpope/vim-fugitive')
call jetpack#add('kien/rainbow_parentheses.vim')
call jetpack#add('tpope/vim-commentary')
call jetpack#add('simnalamburt/vim-mundo')
call jetpack#add('scrooloose/nerdtree')
call jetpack#add('ctrlpvim/ctrlp.vim')
call jetpack#add('Lokaltog/vim-easymotion')
call jetpack#add('jiangmiao/auto-pairs')
call jetpack#add('godlygeek/tabular')
call jetpack#add('sjl/clam.vim')
call jetpack#add('chrisbra/Recover.vim')
call jetpack#add('majutsushi/tagbar')
call jetpack#add('mileszs/ack.vim')
call jetpack#add('Yggdroot/indentLine')
call jetpack#add('kana/vim-scratch')
call jetpack#add('29decibel/vim-stringify')
call jetpack#add('terryma/vim-expand-region')
call jetpack#add('tpope/vim-fireplace')

call jetpack#add('tpope/vim-haml')
call jetpack#add('mattn/emmet-vim')
call jetpack#add('mitsuhiko/vim-jinja')
call jetpack#add('mitsuhiko/vim-rst')
call jetpack#add('ekalinin/dockerfile.vim')
call jetpack#add('vim-scripts/po.vim')
call jetpack#add('cespare/vim-toml')
call jetpack#add('hashivim/vim-terraform')
call jetpack#add('fatih/vim-go')
call jetpack#add('rust-lang/rust.vim')
call jetpack#add('pangloss/vim-javascript')
call jetpack#add('othree/html5.vim')
call jetpack#add('chr4/nginx.vim')
call jetpack#add('tpope/vim-markdown')
call jetpack#add('udalov/kotlin-vim')
call jetpack#add('ziglang/zig.vim')
call jetpack#add('Tetralux/odin.vim')
call jetpack#add('gleam-lang/gleam.vim')
call jetpack#add('MaxMEllon/vim-jsx-pretty')
call jetpack#add('leafgarland/typescript-vim')
call jetpack#add('dense-analysis/ale')

call jetpack#end()

filetype plugin indent on
syntax on

" Theming
if $TMUX != '' && $TERM != 'screen-256color'
    set term=screen-256color
endif

set t_Co=256
color vwilight

let mapleader = ','

" display options
set title
set visualbell
set number
set ruler
set list
set listchars=tab:⇥\ ,trail:·,extends:⋯,precedes:⋯,eol:¬
set encoding=utf-8
set wrap
set linebreak
set showcmd
set laststatus=2
set showbreak=↪

" formatting options
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set smarttab
set autoindent
set smartindent
set shiftround
set noeol
set backspace=indent,eol,start

" buffer options
set hidden
set autoread
set autowrite

" search options
set hlsearch
set incsearch
set ignorecase
set smartcase

set nospell

set wildmenu
set wildmode=list:longest,list:full
set wildignore+=*.o,*.pyc,*.git,*.hg,*.svn,*.DS_STORE,*.sw?,*.py[co],*.orig

" backup options
set noswapfile
set nobackup
set nowritebackup

" highlight JSON as JavaScript
au BufRead,BufNewFile *.json set ft=javascript

" highlight Jinja2 template as Jinja
au BufRead,BufNewFile *.jinja2 set ft=jinja

" ensure Go and Makefile always use tabs instead of spaces
au FileType make,go,java  setl noexpandtab

" set 2-spaces indentation for Ruby, Coffeescript, and YAML files
au FileType coffee,yaml,vim,ruby  setl softtabstop=2 shiftwidth=2 tabstop=2

" Folding
set foldmethod=indent
set nofoldenable

" bind K to grep word under cursor
" nnoremap K :grep! "\b<C-R><C-W>\b"<CR>:cw<CR>

" trailing whitespace
autocmd BufWritePre * :silent! %s/\s\+$//e
autocmd BufWritePre * :silent! %s#\($\n\)\+\%$##

" Highlight the overflow text
" http://stackoverflow.com/questions/235439/vim-80-column-layout-concerns
highlight OverLength ctermbg=red ctermfg=white
au FileType python match OverLength /\%81v.\+/

" Toggles paste mode (http://is.gd/FxlJAH)
set pastetoggle=<F9>

" Turn off search highlighting
nmap <leader>/ :nohl<CR>

" --- Autopairs
let g:AutoPairsShortcutFastWrap = '<C-f>'
let g:AutoPairsMapCR = 0

" --- Rainbow Parentheses
au VimEnter * RainbowParenthesesToggle
au Syntax * RainbowParenthesesLoadRound
au Syntax * RainbowParenthesesLoadSquare
au Syntax * RainbowParenthesesLoadBraces

" --- Airline
let g:airline_theme='dark'
let g:airline_left_sep = ''
let g:airline_right_sep = ''
let g:ttimeoutlen=50

" --- Emmet
let g:user_emmet_leader_key='<C-e>'

" --- Clam
let g:clam_winpos='botright'

" --- Pycomplexity
nnoremap <silent> <F6> :Complexity<CR>

" --- Commentary
autocmd FileType nginx set commentstring=#\ %s
autocmd FileType dockerfile set commentstring=#\ %s
autocmd FileType ldif set commentstring=#\ %s

" --- TagBar
" toggle TagBar with F4
nnoremap <silent> <F4> :TagbarToggle<CR>
" set focus to TagBar when opening it
let g:tagbar_autofocus = 1

" --- NERDTree
nnoremap <F2> :NERDTreeToggle<CR>
autocmd vimenter * if !argc() | NERDTree | endif
autocmd bufenter * if (winnr('$') == 1 && exists('b:NERDTreeType') && b:NERDTreeType == 'primary') | q | endif
let NERDTreeIgnore = ['\.pyc$', '\.egg-info$', '^dist$', '^build$', '^__pycache__$']
let NERDTreeHightlightCursorline=1

" --- Mundo
set undofile
set undodir=~/.vim/undo
nnoremap <F3> :MundoToggle<CR>

" -- ack.vim
" Options
" --vimgrep -> Needed to parse the rg response properly for ack.vim
" --type-not sql -> Avoid huge sql file dumps as it slows down the search
" --smart-case -> Search case insensitive if all lowercase pattern, Search case sensitively otherwise
let g:ackprg = 'rg --vimgrep --type-not sql --smart-case'

" Auto close the Quickfix list after pressing '<enter>' on a list item
let g:ack_autoclose = 1

" Any empty ack search will search for the work the cursor is on
let g:ack_use_cword_for_empty_search = 1

" Don't jump to first match
cnoreabbrev Ack Ack!

" Maps <leader>/ so we're ready to type the search keyword
" nnoremap <Leader>/ :Ack!<Space>

" Navigate quickfix list with ease
nnoremap <silent> [q :cprevious<CR>
nnoremap <silent> ]q :cnext<CR>

if executable("rg")
   set grepprg=rg\ --color=never

  " Use rg in CtrlP for listing files. Lightning fast and respects .gitignore
  let g:ctrlp_user_command = 'rg %s --files --color=never --glob ""'

  " rg is fast enough that CtrlP doesn't need to cache
  let g:ctrlp_use_caching = 0
else
  let g:ctrlp_clear_cache_on_exit = 0
endif

" " --- Ag
" " nnoremap <leader>\ :Ag<SPACE>
" let g:agprg="ag --nogroup --nocolor --column"

" " --- Syntastic
" let g:syntastic_error_symbol = '✗'
" let g:syntastic_warning_symbol = '⚠'
" let g:syntastic_auto_jump = 1
" let g:syntastic_auto_loc_list = 2
" let g:syntastic_aggregate_errors = 1

" let g:syntastic_javascript_checkers = ['jsxhint']
" let g:syntastic_python_checkers = ["flake8"]
" let g:syntastic_python_flake8_args="--ignore=E501"
" let g:syntastic_zig_checkers = ["zig"]
" let g:syntastic_zig_zig_args = ["fmt"]

" --- indentLine
let g:indentLine_color_term = 235
let g:indentLine_char = '¦'

" Faster panes navigation
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" vim-go
" let g:go_bin_path = expand('~/.gobin')
" let g:go_fmt_command = "goimports"
" au FileType go nmap <Leader>gd <Plug>(go-doc)
" au FileType go nmap <Leader>gv <Plug>(go-doc-vertical)
" au FileType go nmap <leader>r <Plug>(go-run)
" au FileType go nmap <leader>b <Plug>(go-build)
" au FileType go nmap <leader>t <Plug>(go-test)
" au FileType go nmap <leader>c <Plug>(go-coverage)
" au FileType go nmap gd <Plug>(go-def)
" au FileType go nmap <Leader>ds <Plug>(go-def-split)
" au FileType go nmap <Leader>dv <Plug>(go-def-vertical)
" au FileType go nmap <Leader>dt <Plug>(go-def-tab)

" Rust
au FileType rust match OverLength /\%99v.\+/
let g:rustfmt_autosave = 1

" Zig
let g:zig_fmt_autosave = 1

" --- ALE
let g:ale_disable_lsp = 1

" let g:ale_completion_enabled = 1
" let g:ale_completion_autoimport = 0
" set omnifunc=ale#completion#OmniFunc

let g:ale_linters = {
\   'python': ['flake8', 'bandit'],
\}

let g:ale_python_flake8_options = '--ignore=E501'

" Only run linters named in ale_linters settings.
let g:ale_linters_explicit = 1

let g:airline#extensions#ale#enabled = 1

let g:ale_echo_msg_error_str = 'ERROR'
let g:ale_echo_msg_warning_str = 'WARNING'
let g:ale_echo_msg_info_str = 'INFO'
let g:ale_echo_msg_format = '[%linter%] %code%: %s [%severity%]'

let g:ale_sign_error = '✗'
let g:ale_sign_warning = '⚠'

" " let g:ale_open_list = 1

nmap <silent> <C-k> <Plug>(ale_previous_wrap)
nmap <silent> <C-j> <Plug>(ale_next_wrap)

" --- coc.nvim
" Having longer updatetime (default is 4000 ms = 4 s) leads to noticeable
" delays and poor user experience.
set updatetime=300

" use <tab> for trigger completion and navigate to the next complete item
function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~ '\s'
endfunction

inoremap <silent><expr> <Tab>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<Tab>" :
      \ coc#refresh()

inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"

" " Use K to show documentation in preview window.
" nnoremap <silent> K :call <SID>show_documentation()<CR>

" function! s:show_documentation()
"   if CocAction('hasProvider', 'hover')
"     call CocActionAsync('doHover')
"   else
"     call feedkeys('K', 'in')
"   endif
" endfunction

let g:go_def_mapping_enabled = 0

" nmap <silent> gd <Plug>(coc-definition)
" nmap <silent> gy <Plug>(coc-type-definition)
" nmap <silent> gi <Plug>(coc-implementation)
" nmap <silent> gr <Plug>(coc-references)
