# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
if [[ -n "$PS1" ]]; then
    export BASH_HOME=~/.bash.d
    export EDITOR='vim'
    export IMAGE_VIEWER='gthumb'
    export BASH_THEME='equator'
    export TERM="xterm-256color"
    export PATH=$HOME/.local/bin:$PATH
    # export BASH_COMPLETION_USER_DIR=$BASH_HOME/completions

    # Pythons!
    export IPYTHONDIR=$HOME/.ipython
    export WORKON_HOME=$HOME/.virtualenv

    if [[ -s $HOME/.python-startup.py ]]; then
        export PYTHONSTARTUP=$HOME/.python-startup.py
    fi

    . "$BASH_HOME/init.sh"

    # krew
    export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"

    export PATH="$HOME/.gobin:$PATH"

    # docker
    export DOCKER_BUILDKIT=1

    export GO111MODULE=on

    if [[ -n $(command -v gh) ]]; then
        eval "$(gh completion -s bash)"
    fi

    for cmd in cue kube-linter grype kubectl minikube; do
        if [[ -n $(command -v $cmd) ]]; then
            eval "$($cmd completion bash)"
        fi
    done

    for cmd in terraform nomad; do
        if [[ -n $(command -v $cmd) ]]; then
            complete -C $cmd $cmd
        fi
    done

    if [[ -n $(command -v rtx) ]]; then
        eval "$(rtx activate bash)"
        eval "$(rtx complete --shell bash)"
    fi

    # lazy load virtualenvwrapper
    if [[ -n $(command -v virtualenvwrapper.sh) ]]; then
        # shellcheck disable=SC2155
        export VIRTUALENVWRAPPER_SCRIPT=$(which virtualenvwrapper.sh)
        . "$(which virtualenvwrapper_lazy.sh)"
    fi

    if [[ -n $(command -v pipx) ]]; then
        eval "$(register-python-argcomplete pipx)"
    fi

    if [[ -n $(command -v pip) ]]; then
        eval "$(pip completion --bash)"
    fi

    for cmd in rustup deno poetry; do
        if [[ -n $(command -v $cmd) ]]; then
            eval "$($cmd completions bash)"
        fi
    done

    if [[ -n $(command -v rustc) ]]; then
        . "$(rustc --print sysroot)/etc/bash_completion.d/cargo"
    fi

    if [[ -n $(command -v nerdctl) ]]; then
        eval "$(nerdctl completion bash)"
    fi
fi
