# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
if [[ -n "$PS1" ]]; then
    export BASH_HOME=~/.bash.d
    export EDITOR='vim'
    export IMAGE_VIEWER='gthumb'
    export BASH_THEME='equator'
    export TERM="xterm-256color"
    export PATH=$HOME/.local/bin:$PATH

    # Pythons!
    export IPYTHONDIR=$HOME/.ipython
    export WORKON_HOME=$HOME/.virtualenv

    if [[ -s $HOME/.pyenv/bin/pyenv ]]; then
        export PYENV_ROOT="$HOME/.pyenv"
        export PATH="$PYENV_ROOT/bin:$PATH"
        export VIRTUALENVWRAPPER_PYTHON=$HOME/.pyenv/shims/python
        eval "$(pyenv init --path)"
        eval "$(pyenv init -)"
        pyenv virtualenvwrapper_lazy >&/dev/null
    fi

    if [[ -s $HOME/.python-startup.py ]]; then
        export PYTHONSTARTUP=$HOME/.python-startup.py
    fi

    # Go
    if [[ -s $HOME/.goenv/bin/goenv ]]; then
        export PATH=$PATH:$HOME/.goenv/bin  # :$HOME/.gobin
        export GO111MODULE=auto
        eval "$(goenv init -)"
    fi

    # NodeJS
    if [[ -s $HOME/.nodenv/bin/nodenv ]]; then
        export PATH=$PATH:$HOME/.nodenv/bin
        eval "$(nodenv init -)"
    fi

    # gopsi
    if [[ -s $HOME/.gopsi/bin/gopsi ]]; then
        export PATH=$PATH:$HOME/.gopsi/bin
        eval "$(gopsi init -)"
    fi

    # Ruby
    if [[ -s $HOME/.rbenv/bin/rbenv ]]; then
        export PATH=$PATH:$HOME/.rbenv/bin
        eval "$(rbenv init -)"
    fi

    source $BASH_HOME/init.sh

    # The next line updates PATH for the Google Cloud SDK.
    if [ -f "$HOME/google-cloud-sdk/path.bash.inc" ]; then source "$HOME/google-cloud-sdk/path.bash.inc"; fi
    # The next line enables shell command completion for gcloud.
    if [ -f "$HOME/google-cloud-sdk/completion.bash.inc" ]; then source "$HOME/google-cloud-sdk/completion.bash.inc"; fi

    # Nim
    if [[ -s $HOME/.nimble/bin/nim ]]; then
        export PATH=$PATH:$HOME/.nimble/bin
    fi

    # krew
    export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"

    # codeql
    export PATH="$HOME/.codeql/codeql:$PATH"

    # docker
    export DOCKER_BUILDKIT=1
fi
