# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
if [[ -n "$PS1" ]]; then
    export BASH_HOME=~/.bash.d
    export EDITOR='vim'
    export IMAGE_VIEWER='gthumb'
    export BASH_THEME='equator'
    export TERM="xterm-256color"
    export PATH=$HOME/.local/bin:$PATH

    # Pythons!
    export IPYTHONDIR=$HOME/.ipython
    export WORKON_HOME=$HOME/.virtualenv

    if [[ -s $HOME/.python-startup.py ]]; then
        export PYTHONSTARTUP=$HOME/.python-startup.py
    fi

    . $BASH_HOME/init.sh

    # krew
    export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"

    # codeql
    # export PATH="$HOME/.codeql/codeql:$PATH"

    export PATH="$HOME/.gobin:$PATH"

    # docker
    export DOCKER_BUILDKIT=1

    export GO111MODULE=on

    export PATH="/opt/zig:/opt/odin:$PATH"

    eval "$(gh completion -s bash)"

    # complete -C /home/iromli/.local/bin/terraform terraform

    . "$HOME/.asdf/asdf.sh"
    . "$HOME/.asdf/completions/asdf.bash"

    . $(asdf where python)/bin/virtualenvwrapper.sh

fi
